name: Node CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: run Postgres
      run: docker run -e POSTGRES_PASSWORD=testpassword -e POSTGRES_USER=testuser -e POSTGRES_DB=heimdall -p 5432:5432 -d postgres
      
    - uses: actions/checkout@master
      with:
        repository: mitre/heimdallts-db
        path: heimdallts-db
    - name: check file
      run: ls   
    - name: Npm install & link
      run: cd heimdallts-db && sudo npm i && npm run build && sudo npm link

    - uses: actions/checkout@master
      with:
        repository: mitre/heimdallts
        path: heimdallts
    - name: check file
      run: ls
    - name: Npm install & link
      run: cd heimdallts && npm i && sudo npm link heimdallts-db
    - name: Npm run
      run: cd heimdallts && npm run start:dev &
      env:
        DATABASE: heimdall
        DATABASE_USER: testuser
        DATABASE_PASSWORD: testpassword
        JWT_SECRET: test
    - name: run curl
      with:
        retry_wait_seconds: 10
        max_attempts: 10
        command: curl localhost:8050
    - uses: actions/checkout@v2
#    - uses: actions/checkout@master
#      with:
#        repository: mitre/heimdallts
#    - name: Docker ps test
#      run: pwd
#    - name: Docker ps test
#      run: ls
#    - name: Docker Build
#      run: docker build -t heimdall-lite .
#    - name: Create Network
#      run: docker network create -d bridge docker_default
#    - name: Docker Run
#      run: docker run -d --network docker_default --network-alias heimdall-lite mitre/heimdall-lite   
    - name: docker ps 
      run: docker ps -a
    - name: npm install
      run: npm install
    - name: Run NPM 
      run: npm run serve &
    - name: run curl
      run: curl http://localhost:8080

