name: Docker Image CI

on: [push]


jobs:
  container:
    runs-on: ubuntu-latest
    container: mitre/heimdall

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
