name: Docker Image CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - uses: actions/checkout@master
#      with:
#        repository: mitre/heimdallts
#    - name: Docker ps test
#      run: pwd
#    - name: Docker ps test
#      run: ls
    - name: Docker Build
      run: docker build -t heimdall-lite .
   - name: Docker Run
      run: docker run -d -p 8080:8080 heimdall-lite   
#    - name: npm install
#      run: npm install
    - name: Run test
      run: npm run test:integration
