name: Node CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: run Postgres
      run: docker run -e POSTGRES_PASSWORD=testpassword -e POSTGRES_USER=testuser -e POSTGRES_DB=heimdall -p 5432:5432 -d postgres
      
    - uses: actions/checkout@master
      with:
        repository: mitre/heimdallts-db
        path: heimdallts-db
    - name: check file
      run: ls   
    - name: Npm install & link
      run: cd heimdallts-db && sudo npm i && npm run build && sudo npm link

    - uses: actions/checkout@master
      with:
        repository: mitre/heimdallts
        path: heimdallts
    - name: check file
      run: ls
    - name: Npm install & link
      run: cd heimdallts && npm i && sudo npm link heimdallts-db
    - name: Npm run
      run: cd heimdallts && npm run start:dev &
      env:
        DATABASE: heimdall
        DATABASE_USER: testuser
        DATABASE_PASSWORD: testpassword
        JWT_SECRET: test
    - name: sleep 60
      run: sleep 120
    - name: run curl
      run: curl localhost:8050/auth/register -X POST -d 'email=test@gmail.com&password=password&passwordConfirmation=password'
    - uses: actions/checkout@v2
      with:
        path: heimdall-lite
    - name: npm install
      run: cd heimdall-lite && npm install
    - name: Run NPM 
      run: cd heimdall-lite && npm run serve &
    - name: run curl
      run: curl http://localhost:8080
    - name: npm test
      run: cd heimdall-lite && npm run test:integration

