name: Docker Image CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@master
      with:
        name: org1/repo1     <-- clone https://github.com/mitre/heimdallts
        ref: refs/heads/release
    - name: Docker ps test
      run: docker ps -a
    - name: npm install
      run: npm install
    - name: Run test
      run: npm run test:integration
