name: Docker Image CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        repository: mitre/heimdallts-db
    - name: check file
      run: ls   
    - name: Npm install & link
      run: npm i && npm run build && npm link

    - uses: actions/checkout@master
      with:
        repository: mitre/heimdallts
    - name: check file
      run: ls
    - name: Npm install & link
      run: npm i && npm link heimdallts-db
    - name: Npm run
      run: npm run start:dev & 
      
    - uses: actions/checkout@v2
#    - uses: actions/checkout@master
#      with:
#        repository: mitre/heimdallts
#    - name: Docker ps test
#      run: pwd
#    - name: Docker ps test
#      run: ls
#    - name: Docker Build
#      run: docker build -t heimdall-lite .
#    - name: Create Network
#      run: docker network create -d bridge docker_default
#    - name: Docker Run
#      run: docker run -d --network docker_default --network-alias heimdall-lite mitre/heimdall-lite   
    - name: docker ps 
      run: docker ps -a
    - name: npm install
      run: npm install
    - name: Run NPM 
      run: npm run serve &
    - name: run curl
      run: curl http://localhost:8080

