name: Docker Image CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - uses: actions/checkout@master
#      with:
#        repository: mitre/heimdallts
#    - name: Docker ps test
#      run: pwd
#    - name: Docker ps test
#      run: ls
#    - name: Docker Build
#      run: docker build -t heimdall-lite .
    - name: Docker Run
      run: docker run -d -p 8080:8080 mitre/heimdall-lite   
    - name: docker ps 
      run: docker ps -a
    - name: Curl 
      run: curl 0.0.0.0:8080
    - name: npm install
      run: npm install
    - name: Run test
      run: npm run test:integration
