name: Docker Image CI

on: [push]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#    - uses: actions/checkout@master
#      with:
#        repository: mitre/heimdallts
#    - name: Docker ps test
#      run: pwd
#    - name: Docker ps test
#      run: ls
#    - name: Docker Build
#      run: docker build -t heimdall-lite .
#    - name: Create Network
#      run: docker network create -d bridge docker_default
#    - name: Docker Run
#      run: docker run -d --network docker_default --network-alias heimdall-lite mitre/heimdall-lite   
    - name: docker ps 
      run: docker ps -a
    - name: npm install
      run: npm install
    - name: Run NPM 
      run: npm run serve &&
    - name: NPM test
      run: npm run test:integration
